# This is a basic workflow to help you get started with Actions

name: Discord Notifications

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Actions Status Discord
      # You may pin to the exact commit or the version.
      # uses: sarisia/actions-status-discord@e5291389ca2723d0375650390c20a60dbe9ed819
      uses: sarisia/actions-status-discord@v1.8.6
      with:
        # Discord webhook endpoint. If not set, env.DISCORD_WEBHOOK will be used.
        webhook: https://discordapp.com/api/webhooks/896951532979896330/m3Tt-_7Dp4QCoRQ2wfRxodudldzBql9Uty-EeQ0D2AomXf3RcDhomuvMFHQfRrHT95HB
        title: 'title'
        description: 'desc'
        color: 0x00FF00
        username: 'user'
        nocontext: true
        noprefix: true
        nodetail: false
